model_kwargs:
  learning_rate: 0.00025
  gamma: 0.99
  n_steps: 1024
  batch_size: 128
  n_epochs: 10
  clip_range: 0.2
  ent_coef: 0.01
  gae_lambda: 0.95
  vf_coef: 0.5
  max_grad_norm: 0.5
  policy_kwargs:
    net_arch: [256, 256]
    activation_fn: Tanh
